```mermaid
gantt
dateFormat  YYYY-MM-DD
title lernOS Roadmap 2016-2022

section lernOS Core
lernOS for Orgs           :active,	des1, 2017-01-01,2017-12-31
lernOS for You                      :active,    des1, 2018-09-17,2019-12-31
lernOS for Teams          :active,	des1, 2020-01-01,2020-12-31

section lernOS Toolbox
Expert Debriefing                :active,    des1, 2019-03-01,2019-12-31
Podcasting                :active,    des1, 2019-03-01,2019-12-31
Sketchnoting                :active,    des1, 2019-03-01,2019-12-31

section lernOS Events
loscamp19                 :done,    des1, 2019-06-25
clc19ko                   :active,    des1, 2019-09-12,2019-09-13
gkc19                     :active,    des1, 2019-11-21,2019-11-22
```

